poll/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('startapp.urls')),
    path('pollapp/', include('pollapp.urls')),
    path('admin/', admin.site.urls),
]

pollapp/urls.py
from django.urls import path

from . import views

app_name = 'pollapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.choice, name='choice'),
    path('<int:question_id>/score/', views.score, name='score'),
    path('<int:question_id>/user_vote/', views.user_vote, name='user_vote'),
]

startapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

pollapp/models.py
from django.db import models

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')



class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

startapp/models.py
from django.db import models

# Create your models here.

pollapp/views.py
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Question, Choice


def index(request):
    ques_list = Question.objects.order_by('-pub_date')[:5]
    context = {'question_list': ques_list}
    return render(request, 'pollapp/index.html', context)

def choice(request, question_id):
    try:
        ques = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question not exist")
    return render(request, 'pollapp/choice.html', {'question': ques})


def score(request, question_id):
    ques = get_object_or_404(Question, pk=question_id)
    return render(request, 'pollapp/score.html', {'question': ques})


def user_vote(request, question_id):

    ques = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = ques.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):

        return render(request, 'pollapp/detail.html', {
            'question': ques,
            'error_message': "Didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('pollapp:score', args=(ques.id,)))

startapp/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'startapp/index.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Poll app {% block title %}{% endblock %}</title>
    <style>
        body {background-color: rgb(188, 207, 241);}
        p    {color: rgb(76, 77, 77);}
        </style>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4">
        <a class="navbar-brand" href="{% url 'index' %}">Poll App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pollapp:index' %}">Available Polls</a>
            </li>
        </div>
      </nav>
    <div class="container">
        <div class="row">
            <div class=".col-md-6 m-auto">
                {% block content %}
                {% endblock%}
            </div>
        </div>
    </div>
</body>

</html>

templates/pollapp/choice.html
{% extends 'base.html' %}
{% block content %}
<br>
<h1 class="text-center mb-3">{{ question.question_text }}</h1>

{% if error_message %}
<p class="alert alert-danger">
    <strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'pollapp:user_vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <div class="form-check">
        <input type="radio" name="choice" class="form-check-input" id="choice{{ forloop.counter }}"
            value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    </div>
    {% endfor %}
    <a class="btn btn-dark btn-sm mb-3" href="{% url 'pollapp:index' %}">Back</a>
    <center><input type="submit" value="Vote" class="btn btn-dark " /></center>
</form>
{% endblock %}

templates/pollapp/index.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center mb-4">Available polls &#129047;</h1>
{% if question_list %}
{% for question in question_list %}
<div class="card-mb-3">
    <div class="card-body">
        <p class="lead">{{ question.question_text }}</p>
        <a href="{% url 'pollapp:choice' question.id %}" class="btn btn-primary btn-sm">Vote</a>
        <a href="{% url 'pollapp:score' question.id %}" class="btn btn-dark btn-sm">Results</a>
    </div>
</div>
{% endfor %}
{% else %}
<p>No polls available</p>
{% endif %}
{% endblock %}

templates/pollapp/score.html
{% extends 'base.html' %}
{% block content %}
<h1 class="mb-5 text-center">{{ question.question_text }}</h1>

<ul class="list-group mb-5">
    {% for choice in question.choice_set.all %}
    <li class="list-group-item">
        {{ choice.choice_text }} <span class="badge badge-primary float-right">{{ choice.votes }}
            vote{{ choice.votes | pluralize }}</span>
    </li>
    {% endfor %}
</ul>

<a class="btn btn-dark" href="{% url 'pollapp:index' %}">Back</a>
<a class="btn btn-dark" href="{% url 'pollapp:choice' question.id %}">Vote</a>
{% endblock %}

templates/startapp/index.html
{% extends 'base.html' %}
{% block content %}
<br>
<br>
<br>
<center>
<h1>Welcome to the voting website!</h1>
        <p>You can vote and see the results.</p>
        <a class="btn btn-primary" href="{% url 'pollapp:index' %}">View Polls</a></center>

{% endblock %}